Entry.create!(name: "heriberto pere")
Entry.create!(name: "Alma decinia")
Entry.create!(name: "rauls armando perez")
Entry.create!(name: "jose heriberto perez")
Entry.create!(name: "claudia cecilia")
Entry.create!(name: "ma concepcion magania")
Entry.create!(name: "jsoe alberto carrasco")
Entry.create!(name: "Elizabeth martinez")
Entry.create!(name: "francisco cardenas san")
Entry.create!(name: "Herbert andres parra")
